apiVersion: v1
kind: Namespace
metadata:
  name: simplek8s-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-map
  namespace: simplek8s-secret
data:
  MySecret: bVlwQHNzdzByZA== # base 64 encoded value not really secret. 
  MyFileAsSecret: iVBORw0KGgoAAAANSUhEUgAAAwAAAAJABAMAAADIgBxlAAAAMFBMVEWy0esxbOb///9OgujM2/k8deeZt/Njkunb5fulxex0n+uXvOuMsuyBqurs8vy4zfcpHilCAAANT0lEQVR42uzZP4oUQRiG8S/tbTd4GZoFPcWE/rlEpwseYkLxEoLBQEcu0oGZMsGkwlxAkLmPKNjisrtUz1RPfVX1/I7wvVQH/RgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjVfu6l7tVXQxJDrz+6L4YE9pq8N1zcTmKBhA76z2vDRR10zxvDBf2UWCChox7w1nAho8QC6TSjHnH7wbC45k5igXSajZ5wwwILazcSCyQQeH/phl9zC2rXEguk82ytAKvvhkns+7NAOtdrBVr9MER33StYxwLRXfWaoftkiGroFYhMuYRtr7lYIKKtTvDOEMlewQjFZl7uzwKRHDQDqd7T/QnFcfI7CyR0VDBC8QJGiQXSaUYFIxSb0/uzwBn5PRih2BzfnwWWye//EIrja9eKasUCsfPvhFBsGdyfBaLn9wmpfpIgv0uk+kmS/E6qnyTJ76T62AbNQar/LXl+J9Vb8vxLKM7l/izwhJ1mINX/5SO/E4rzuT8LnJvfCcUTV/l9jlvDqfmXUGwF3J8Fzsm/hOIS7s8CZ+R3Ur2Z2/xOqk+ffwnFudyfBU7P76R6z/mdVB/mysH9a071g4v715vqB7lR5QJbOVJhqt/LlepCsbP7V7fATu5UleoPcqiiUOzy/hUtcJRTlaR6t/evI9U3oxwrPxT7vn/5CzQbOVd2KPZ//7IXaDO4f8mpPo/7l5vqc7l/sQvcKRvPrUAflZGXVpzWSX8M05X3EfqmrLywwuT1AAp8Ar/YuZfXmeIwDOCjX9M0Mz/lMcYtl3zd5XYUSSEisuFgIQtCsRGOJCvllstCjVKyUINy2fkTxsJKaigrlJFbKRGWche+w5yv9x3H+/BZs/HgnOe8DydhzIocFzOvoF8MylHphTlco9E8zJmeY9KEOcNzTDIfQYer5IiUYRDTi2gBBjGNpg0+g7mewjUYNCTHw+BLEDAsx8NcD2brwgbfQqneQ4swKUfD4JcggKkIlGASTxHogUk8RaAPTOK5yRi7B3/CdBc22cOYPkgn6I5Vl29v3nz9wkx0A1MTi9EFc7bvd59NeHMOXVDNkShC39y37jvPb0Efy1C9L7QNOuU8RxPo4rnLF6BsVsu1MXUT8L+J/Ykedt79xDJ88L+JdbeHVW+4n3oWQ1O/HIcGVPi//r5HMTSQNbE6FN1zv/QManj+nUYEPXtcB4ehheckAz3rXUevoYCqiZWhZmjLdTS1Djmqk4xeD6u+dClMi6GF478ULUDLXpfKY2jZkWOQh5LhLqUmpKhOMjUoOeFSmgYVLOO4BnSsdqkthgaWcVwCFdX9LrUJ0f8mpt7DZrsAB/43Me0eVmm5AFMjKOAYx/VCxTwX5AF+E18TK0FDdb8LMiGGCNFJpgca1rhAhyBCdJLJQ8NLF0DSBfia2BUoGOiC1fBb+E4yTSg464JNggTROC6BXMX9hggCROO4uHuP4KnLt969e+1VS/MxTHeSKULBiba//KcjfFS51DaCiZCgGcf1Qm5Q2wFEhK8q21wbCQRoxnEFyK3pPMI673yH/jcxpR620XmW4Ae7nGfc/yamM4urOM8xeC524T2IYRzXgNhI//d2DE/V/3PyAqEIm1gdYju9958EbQxquR+Mx29gO8lEEFuY7uLo3yzHIBRhE4shNTTtC75fF+oIxNfEyhAb4H6wAb72n+z2IRRdE+ur/wiYjJ+6qvEQ4BrHFfQfATX81ECNhwDXOC4PqUrIpeWltAnQnWRqkBoY8oFhjfe4CMc1jmtAakTA4MQbr9xHOK5xXAIR/xg2KexH//NNLILUy6DPCyMVTvNU4zhIVd33orBHNgQYxnFlSA0N/MS8UdaF2cZxJUgNcd95iA7WCccpZCeZHoj4L0ENdDBM9hrE1sTykJrx/UtojA6q37+IjkYYtiZ2BVI3Q5YO/ifRKQjD1sSakDoR+ht6huw9lGwcl0Bqf+j35cHfz9QRhu0kE0OoGvZtx/92FCMMVxMrQsTfZCXKP8PHdZLpVe5hU5FCS/SPtrnGcSVIDQw7sPgHnA3/dBOT97CR4Vu3jbJtENU4rg+kBoR9Xfa/SC9AOJ5xnLyHDQ7vtTNEwwiucVwdEv6noLFIYaXoYxDXSSaBVH/3rVHhmY1CGK4mFkPE/+2s/YfGRzWOKyOLAAbLAmBqYn0h4z9R1Z/bPqZxXCHTAKY+OXjkeCs4AKaTTD6rAJ4cWXqk9Zt/ApiaWC2TAAa0RH8FMZ1kGhzPALvjuDpHAHabWMQRgN2TDDgCMDuOKyPY3xmA1XFciSUAqyeZAksAVptYniUAq+O4GksAVptYkyUAq+O4hCUAqyeZKJsABojvASRNrIhsAhgpPkmSnGR6MwpgqHgXRDKOK2UQgP//fCf4Z5tYT0YBYKf0/64kOcn0ySqAoRp/AxGM465AQBIA5nv/uV8oinFcPbMAsPbO9Y/O4XcxnGSS7AKQY2hiMU8AJsdxRfAEYLKJ9WUKwOI4rsAUgMWTTA9TABabWI0pAIsnmQZTABbHcXWmACw2sYgpAIsnGTAFYHAcV4aCvycAe+O4ElcA9k4yBa4A7DWxPFcA9sZxNa4A7DWxJlcA9sZxCVcA9k4yEVcA5ppYEWLV3a+OHNnvvjXhSAoHF/1g+ZYYQvZOMr2Qqpxxap5GkLE3jitBaqNTNPmfa2I9EFrtVC2GiL2TTB/IVPc7VRNiSNgbx12BzACnbAEk7I3j6pC56t77m54C1k4yCUQqTl2MtCiaWAyRIU5dDQLmxnFFyIxw6u4jNYIm1hcyO5268ZCwNo4rQGajUzcOqRGcZKQ97KVTNw2pETSxGmQWOnVjkBrBSabBF4CtcVydLwBbTSziC8DWSQZ8AZgax5URwEoAlsZxfRkDsNTECowBWGpiecYALI3jaowBWGpiTcYALI3jEsYALJ1kIsYALDUxMAZgqIn1IoiVAOyM40qcAdgZx/VwBmDnJNOHMwA747grCGIlADvjuCZnAO/Yu2PcJqIojMJGERo5MymeolSsYkqW4RLR01F4KRGaBXgJLliAl+CG9cB1CgRNPFEk33PuO1v4iy+PeTxzTmJ75wCck9jOOQDmcty2OQfAXI6brANQPskM1gEon2TurANQTmIfrANQTmKntjLKAJTLcQfrAJTLcbN1AMonmZ11AMgnmbGtjjIA43Lcg3cAxkls8A7AOIl99A7AuBz37B2AcTnu5B2AcRLbewdgfJKZvQMwTmLNOwDiJDa2N0QZgHASm8wDEE5i9+YBCLcTB/MAhKNwH2BdfYA+QB+gD9AH6AP0P0Mtf4aqD2KE/ya2NQ+AuJ678w7AuKAu/h7AuJl19A7A+CR55x2AcT26X8xaXzoEcg7A+CS82SzWAb5sGGn/jxjhGHbp4ByA8Ueo+LEOwr/EvbTdGQd4RPw7xEtH4wAUgqPJOACG4P58fYIG3wAcgqPtbBuAcS/3b8+2AUgER5NtABTB0cE1AIvgaHANwCL40mwagEZwtJgGoBEcTaYBIJ/C/u3gGYBHcDR4BgASHM2WAYgER4tlACLB0WQZAElwdHAMwHm0+/8GxwBQgqPZMACV4GgxDEAlOBoNA2AJjs78AbgERwN/ADDB0UwfgExwtNAHIBMcjfQB0ARHZ/YAbIKjgT0AnOBoJg9AJzhayAPQCY5G8gB4gqMzdwA+wdHAHYDwOs0VzdQBDARHC3UAA8HRCB3gSUHw2xj+9e3d+95eDflrAdd035BJCI7mBsxCcLQ0YJ83nsZdw+UhODo1XB6CoQyLCEYyTHkd69p+NFgmgokMP4HeplEy7CIYyLCM4GjfQNkIxjHMeCJ3XVsQwz6CYQz7CIYxLCQYxbCR4OiuQTISTGLYSTCI4U8baxCGCT8abGbYSjCGYSvBFIa9BEfHlj4vwdFDS5+YYATDZoIRDJsJJjDsJhjAsJtgAMNygtMzbCc4PcN2grMz7Cc4OcN+gpMzXIDg1AxXIDg1wxUIzsxwDYITM1yD4MQMFyE4OrSEMX+nRMRwFYKzMlyH4KQMf91Uamrpwv1ap4zhSgSnZLgSwZeSMfxYiuDoZ0tVLYITMlyM4HQMVyM4GlqiBI+koxmuR3Cyh+QsL7RiGS5IcCqGKxKciuGSBCd6SM70QiuS4ZoEJ2K4KMFpGK5KcBqGyxKchOG6BCdhuC7B0dhunuqR9PWd23tV8gezBQyXJjgBw7UJTsBwbYITMFyc4JszXJ3gmzNcnuD1DHeC/6RhuBO8muFO8CUJw53g3+3dQQrCMBBA0RzATRY9i4iX8C4uPZYLryculGJLYAqhTPreHcKnNJkJZ1iCv0bIsASHMyzBPyNkWILDGZbguexj1SU4nGEJnkmfYQkO7/qU4H+Zt5uMuSosUYYHXRWWJsMSvPOuz1thzwxPEhzNsAQvJc6wBIfnuUrwirQZvhSCg+QkeFXSDEvwpjd7JrQuJD0CDkD0Y0wBmrJdUPEnrOFZu7sWGl61s0eh6XSv/UznA48lAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgI83yHxldLjJ8ysAAAAASUVORK5CYII=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: simplek8s-secret
  labels:
    app: weather-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: weather-forecast
        service: webapi
    spec:
      containers:
        - name: webapicontainer
          image: joymon/simplek8sconfiguration:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: MyEnvVarFromMySecret
              valueFrom:
               secretKeyRef:
                name: secret-map
                key: MySecret
          volumeMounts:
            - name: secret-map-vol
              mountPath: /app/lock.png
              subPath: MyFileAsSecret
      volumes:
        - name: secret-map-vol
          secret:
            secretName: secret-map
---
apiVersion: v1
kind: Service
metadata:
  name: webapiservice
  namespace: simplek8s-secret
  labels:
    app: weather-forecast
    service: webapi
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort : 80
      protocol: TCP
  selector:
    service: webapi