# This won't work by just using Kubectl. Require Helm to replace the file contents.
apiVersion: v1
kind: Namespace
metadata:
  name: simplek8s-configmap-file

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-configmap
  namespace: simplek8s-configmap-file
data:
  k8sproduction.appsettings.json: |-
   {{ .Files.Get "host/appsettings.Production.json" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: simplek8s-configmap-file
  labels:
    app: weather-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: weather-forecast
        service: webapi
    spec:
      containers:
        - name: webapicontainer
          image: joymon/simplek8sconfiguration:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
          volumeMounts:
           - name: appsettings-volume
             mountPath: /app/appsettings.json
             subPath: k8sproduction.appsettings.json
      volumes:
        - name: appsettings-volume
          configMap:
             name: appsettings-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: webapiservice
  namespace: simplek8s-configmap-file
  labels:
    app: weather-forecast
    service: webapi
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort : 80
      protocol: TCP
  selector:
    service: webapi
